### PR TITLE
update slurm adapter for ORNL andes cluster

### PR DESCRIPTION
**Pull request by wjlei1990**

### CODE REVIEW

**Comment by mtitov** [comment]
hi @wjlei1990, can you please try to add `'andes' in self.rm.host.lower()` to the line 577 instead of 583 (right after `longhorn`)?

**Comment by wjlei1990** [comment]
For now, I don't set "--ntasks" or "-n" in my slurm header. I don't know if it is needed or not...

**Comment by mtitov** [comment]
RP will set a number of requested cores for this option (as an upper threshold). Don't have a strong opinion about this, since the following option `--ntasks-per-node` will be set (we don't have a resource config for Andes yet, but `cores_per_node` will be set there and that corresponding value will be used for `--ntasks-per-node`).

**Review by andre-merzky — APPROVED** [review]
LGTM

**Pull request merged**
