### PR TITLE
Revert "Fix bridges GPU gres flag"

### PR DESCRIPTION
**Pull request by iparask**
Reverts radical-cybertools/radical.saga#792

### CODE REVIEW

**Comment by iparask** [comment]
Sorry @andre-merzky I did not change the target branch to devel from PR 792.

**Comment by andre-merzky** [comment]
Oy, I see... - sorry, I missed that, too.  But I think I can just push a new release.

**Comment by iparask** [comment]
Better not. I would say revert and let me open a PR for devel because it is missing the latest changes. I made a small mess there.

**Comment by andre-merzky** [comment]
*\me tips hat*

**Pull request merged**
