### PR TITLE
Fix/issue 707

### LINKED ISSUE #707: SAGA to expose environment variable about SMT setting for Summit
Just follow up ticket from an email thread with ORNL. There are no explicit env variables that expose that, we will have to look at the cpuset (at /sys/fs/cgroup/cpuset/cpuset.cpus) and parse it. Easier solution would be to have SAGA expose an env variable.

### PR DESCRIPTION
**Pull request by andre-merzky**
This fixes #707

### CODE REVIEW

**Comment by mturilli** [comment]
@iparask To add unit test and review

**Comment by andre-merzky** [comment]
unit test has been fixed.  I made a stupid mistake and merged the SMT semantics into `feature/summit` when cleaning up there, and only realized after several changes - apologies.  :-(

**Comment by andre-merzky** [comment]
The dir rename is done.

**Comment by andre-merzky** [comment]
For the reasoning behind the adaptor rename see discussion in #715

**Comment by andre-merzky** [comment]
This is now implemented in the feature/summit branch.

**Pull request closed without merging**
